# Generated by Django 2.0 on 2018-10-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0011_auto_20181018_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_users',
            name='pincode',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='track_users',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
