# Generated by Django 2.0 on 2018-10-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0012_auto_20181024_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_users',
            name='city',
            field=models.TextField(default='asdf', max_length=100),
        ),
        migrations.AddField(
            model_name='user_details',
            name='city',
            field=models.TextField(default='asdf', max_length=100),
        ),
    ]
