# Generated by Django 2.0 on 2018-10-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefundo', '0013_auto_20181024_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='people_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='track_users',
            name='city',
            field=models.TextField(default='asdf', max_length=10),
        ),
    ]
